# ==============================================================================
# CryoEvap-v2 Environment Configuration
# ==============================================================================
# Project: CryoEvap-v2 - Cryogenic Evaporation Simulation
# Author: Felipe Huerta
# Maintainer: Ignacio Tapia
# Email: fnhuerta@uc.cl (Author), iptapia@uc.cl (Maintainer)
# Version: 2.0.0
# Created: 2025
# Last Updated: 2025-09-23
# Description: Conda environment for CryoEvap-v2, a simulation tool for cryogenic liquid storage.
# Repository: https://github.com/Ignacio-TG/CryoEvap-v2
# License: GPL
# ==============================================================================

name: CryoEvap
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.2.3
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scipy=1.15.2
  - CoolProp==6.6.0
  - ipython
  - psutil
